# Generated by Django 5.1.7 on 2025-10-06 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="discount", name="is_active",),
        migrations.AddField(
            model_name="discount",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_review", "In Review"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                ],
                default="in_review",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_discounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="ends_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discount", name="starts_at", field=models.DateTimeField(),
        ),
    ]
