# Generated by Django 5.1.7 on 2025-10-14 19:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="photo_url", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_unit",
            field=models.CharField(
                blank=True,
                choices=[("per_piece", "Per piece"), ("per_kilogram", "Per kilogram")],
                default="per_piece",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
