# Generated by Django 5.1.7 on 2025-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_photo_url_alter_product_price_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
