# Generated by Django 5.1.7 on 2025-10-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_external_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product", unique_together={("store", "name", "external_id")},
        ),
    ]
