# Generated by Django 5.1.7 on 2025-10-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product", unique_together={("brand", "external_id")},
        ),
    ]
