# Generated by Django 5.2.7 on 2025-10-20 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("name", "Name"),
                            ("photo", "Photo"),
                            ("price", "Price"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("discount_image_base64", models.TextField(blank=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported"),
                            ("ACCEPTED", "Accepted"),
                            ("DENIED", "Denied"),
                        ],
                        default="REPORTED",
                        max_length=16,
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="catalog.discount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="catalog.product",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("product__isnull", False), ("discount__isnull", True)
                            ),
                            models.Q(
                                ("product__isnull", True), ("discount__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="report_exactly_one_target",
                    )
                ],
            },
        ),
    ]
