# Generated by Django 5.2.7 on 2025-10-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_shoppingcart_unique"),
    ]

    operations = [
        migrations.RemoveField(model_name="shoppingcart", name="brand",),
    ]
