services:
  backend-money:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend-money:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend-money
    restart: unless-stopped