services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/media:/app/media
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - backend
    restart: unless-stopped